### ISSUE TITLE
Registration page

### ISSUE THREAD

**Issue by panpan2557** [Bookie-TSP/Bookie-FrontEnd#3]

**Comment by Nathakorn** [comment]
The form (label, button and blank) is complete. Need to add more design

**Comment by pwatakul** [comment]
Please rework in defect: https://docs.google.com/document/d/1n-axq3YniLcaurrrsINEt64DhfOXH9t464a9RShb0DI/edit?usp=sharing

**Comment by pwatakul** [comment]
Please rework in defects: https://docs.google.com/document/d/1pM858BqQ3sXZrmh8gcBqR1BCM8xpM-xmsBubwZudQ2M/edit?usp=sharing
