### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by panpan2557** [Bookie-TSP/Bookie-FrontEnd#4]

**Comment by panpan2557** [comment]
switch the task between me and @naneen

**Comment by panpan2557** [comment]
Finish with the navigation bar.
Wait for @tandooky to merge the branch

**Comment by pwatakul** [comment]
Please rework : https://docs.google.com/document/d/1oqPVJrx0yta17HPO5NYuKpOr-GsSHPg3Z9YqenKuPFA/edit?usp=sharing

**Comment by panpan2557** [comment]
The rework was done by @tandooky. Since, he has merged the branch and fixed the code according to the standard
