### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by panpan2557** [Bookie-TSP/Bookie-FrontEnd#6]

**Comment by mntrq** [comment]
User can login but keeping him signed in is not finish yet

**Comment by pwatakul** [comment]
Please rework : https://docs.google.com/document/d/1lqasu2ZjByIlDcvPp7tpUZ2uQTj603PRYDhV4PRYcPA/edit?usp=sharing

**Comment by mntrq** [comment]
Done on login-rework1 branch
